name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: uv pip install -e .[dev]
      - name: Run tests
        run: uv run pytest
